services:
  frontend:
    container_name: games-frontend
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/