name: Build and push container to Google Artifacts Registry
on:
  release:
    types: [created]
jobs:
  push-to-artifacts:
    name: Build and push image to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bq-connector-frontend
      PROJECT_ID: bqconnect-349116
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Get current version tag
        id: get_tag
        run: echo "::setoutput name=tag::${GITHUB_REF#refs/tags/}"

      - name: Authenticate GCP
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v0
    
      - name: Configure Docker client
        run: |-
          gcloud auth configure-docker --quiet 
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push image to artifacts registry
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |-
          # echo Version:$TAG
          docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/bq-images/$IMAGE_NAME:latest
          # docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/bq-images/$IMAGE_NAME:$TAG
          docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/bq-images/$IMAGE_NAME:latest
          # docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/bq-images/$IMAGE_NAME:$TAG
